"""Move slug from separate table to engagement table

Revision ID: e572f7d709c5
Revises: e1f7a3c9b2d5
Create Date: 2026-06-15 14:06:46.186253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e572f7d709c5'
down_revision = 'e1f7a3c9b2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_slug', table_name='engagement_slug')
    op.add_column('engagement', sa.Column(
        'slug', sa.String(length=256), nullable=True))
    # Migrate data from engagement_slug to engagement
    op.execute("""
        UPDATE engagement e
        SET slug = es.slug
        FROM engagement_slug es
        WHERE e.id = es.engagement_id
    """)
    # If there are any engagements without a slug, auto-generate from the name
    op.execute("""
        UPDATE engagement
        SET slug = regexp_replace(lower(name), '\\s+', '-', 'g')
        WHERE slug IS NULL
    """)
    op.alter_column('engagement', 'slug',
                    existing_type=sa.String(length=256),
                    nullable=False)
    op.create_unique_constraint(
        'uq_slug_per_tenant', 'engagement', ['slug', 'tenant_id'])
    op.drop_table('engagement_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_slug_per_tenant', 'engagement', type_='unique')
    op.drop_column('engagement', 'slug')
    op.create_table('engagement_slug',
                    sa.Column('created_date', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_date', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('engagement_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('slug', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=False),
                    sa.Column('created_by', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['engagement_id'], [
                        'engagement.id'], name='engagement_slug_engagement_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='engagement_slug_pkey'),
                    sa.UniqueConstraint(
                        'engagement_id', name='engagement_slug_engagement_id_key'),
                    sa.UniqueConstraint(
                        'slug', name='engagement_slug_slug_key')
                    )
    op.create_index('idx_slug', 'engagement_slug', ['slug'], unique=False)
    # ### end Alembic commands ###
